// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_FC8W9ifKFzTtT2StVr_PAUWAebGAAY',
    appId: '1:780900514083:web:fc0cb1b77dbd1c17873496',
    messagingSenderId: '780900514083',
    projectId: 'attendance-system-91e45',
    authDomain: 'attendance-system-91e45.firebaseapp.com',
    storageBucket: 'attendance-system-91e45.appspot.com',
    measurementId: 'G-86S021YKPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYTURUg_a_H81crkKrgvGtHxSK_5_JpUk',
    appId: '1:780900514083:android:2f52b457c5ea7b50873496',
    messagingSenderId: '780900514083',
    projectId: 'attendance-system-91e45',
    storageBucket: 'attendance-system-91e45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc99rNDbkxL-ZNjGgr5nbOQfjXli8JIy0',
    appId: '1:780900514083:ios:4cf26878555c3a9a873496',
    messagingSenderId: '780900514083',
    projectId: 'attendance-system-91e45',
    storageBucket: 'attendance-system-91e45.appspot.com',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc99rNDbkxL-ZNjGgr5nbOQfjXli8JIy0',
    appId: '1:780900514083:ios:bd14a9e1c2100785873496',
    messagingSenderId: '780900514083',
    projectId: 'attendance-system-91e45',
    storageBucket: 'attendance-system-91e45.appspot.com',
    iosBundleId: 'com.example.attendanceSystem.RunnerTests',
  );
}
